# File: clinichub/settings.py
"""
Django settings for ClinicHub project.
Generated by 'django-admin startproject' using Django 5.2.x.

This version is hardened for:
- local development
- Render / production deployment
- test execution
- optional apps/modules
"""

from __future__ import annotations

import sys
from importlib.util import find_spec
from pathlib import Path
from urllib.parse import urlparse

import dj_database_url
from decouple import config
from django.contrib.messages import constants as messages


# ===================================
# Helpers
# ===================================
def env_str(name: str, default: str = "") -> str:
    try:
        return str(config(name, default=default)).strip()
    except Exception:
        return default


def env_bool(name: str, default: bool = False) -> bool:
    val = env_str(name, str(default)).lower()
    return val in {"true", "1", "yes", "y", "on"}


def env_int(name: str, default: int) -> int:
    try:
        return int(env_str(name, str(default)))
    except Exception:
        return default


def env_float(name: str, default: float) -> float:
    try:
        return float(env_str(name, str(default)))
    except Exception:
        return default


def _module_exists(module_path: str) -> bool:
    try:
        return find_spec(module_path) is not None
    except Exception:
        return False


def _csv_list(value: str) -> list[str]:
    return [x.strip() for x in (value or "").split(",") if x.strip()]


def _is_testing() -> bool:
    argv = " ".join(sys.argv).lower()
    argv_padded = f" {argv} "
    return (" test " in argv_padded) or ("pytest" in argv) or env_bool("TESTING", False)


def _normalize_allowed_host(host: str) -> str:
    """
    Normalize host entries for ALLOWED_HOSTS:
    - accepts plain hosts, full URLs, hosts with ports
    - preserves leading dot wildcard style (.example.com)
    """
    host = (host or "").strip()
    if not host:
        return ""

    if host in {"*", ".localhost"}:
        return host

    if host.startswith("http://") or host.startswith("https://"):
        try:
            parsed = urlparse(host)
            host = parsed.netloc or ""
        except Exception:
            return ""

    # remove credentials if any
    host = host.split("@")[-1].strip()

    # keep bracket IPv6 if present, but strip port safely when possible
    if host.startswith("["):
        # e.g. [::1]:8000
        if "]" in host:
            end = host.index("]") + 1
            bracketed = host[:end]
            return bracketed
        return host

    # normal host: strip port
    host = host.split(":")[0].strip()
    return host


def _site_host(site_url: str) -> str:
    """
    Extract hostname from SITE_URL or plain host.
    """
    raw = (site_url or "").strip()
    if not raw:
        return ""
    if raw.startswith("http://") or raw.startswith("https://"):
        try:
            return _normalize_allowed_host(urlparse(raw).netloc)
        except Exception:
            return ""
    return _normalize_allowed_host(raw)


def _normalize_host_for_csrf(host: str) -> str:
    """
    Convert ALLOWED_HOSTS entry into CSRF_TRUSTED_ORIGINS-compatible host token.
    """
    host = (host or "").strip()
    if not host or host == "*":
        return ""

    host = _normalize_allowed_host(host)
    if not host:
        return ""

    # ALLOWED_HOSTS may use ".example.com" -> CSRF should use "*.example.com"
    if host.startswith("."):
        return f"*.{host.lstrip('.')}"
    return host


def _build_csrf_trusted_origins(hosts: list[str], site_url: str) -> list[str]:
    origins: set[str] = set()

    # Add SITE_URL origin first
    try:
        parsed = urlparse(site_url)
        if parsed.scheme and parsed.netloc:
            origins.add(f"{parsed.scheme}://{parsed.netloc}")
        else:
            host_only = _site_host(site_url)
            if host_only:
                origins.add(f"https://{host_only}")
    except Exception:
        pass

    for h in hosts or []:
        h2 = _normalize_host_for_csrf(h)
        if not h2:
            continue

        # Local/testing hosts -> allow both schemes
        if h2 in {"127.0.0.1", "localhost", "testserver", "::1", "[::1]"}:
            origins.add(f"http://{h2}")
            origins.add(f"https://{h2}")
        elif h2.startswith("*."):
            origins.add(f"https://{h2}")
        else:
            origins.add(f"https://{h2}")

    return sorted(origins)


# ===================================
# Paths / Runtime flags
# ===================================
BASE_DIR = Path(__file__).resolve().parent.parent

# Auto-detect project package name (case-safe on Linux/Render)
PROJECT_PACKAGE = Path(__file__).resolve().parent.name

TESTING = _is_testing()

# ===================================
# Core / Debug
# ===================================
DEBUG = env_bool("DEBUG", False)
APPEND_SLASH = True

# SECRET_KEY: strict in production, convenient fallback in dev/tests
SECRET_KEY = env_str("SECRET_KEY", "")
if not SECRET_KEY:
    if DEBUG or TESTING:
        SECRET_KEY = "dev-insecure-secret-key-change-me"
    else:
        raise RuntimeError("Missing SECRET_KEY environment variable in production.")

# ===================================
# Hosts / Site URL
# ===================================
SITE_URL = env_str("SITE_URL", "https://clinichub.onrender.com").rstrip("/")

_local_hosts = ["localhost", "127.0.0.1", "::1", "[::1]", "testserver"]

if DEBUG:
    ALLOWED_HOSTS = _local_hosts.copy()
    # allow optional extra hosts during local dev (e.g. phone LAN IP)
    ALLOWED_HOSTS.extend(_csv_list(env_str("ALLOWED_HOSTS", "")))
else:
    render_host = env_str("RENDER_EXTERNAL_HOSTNAME", "")
    env_hosts = _csv_list(env_str("ALLOWED_HOSTS", ""))

    hosts: list[str] = []
    hosts.extend(env_hosts)

    if render_host:
        hosts.append(render_host)

    # Also derive from SITE_URL automatically
    site_host = _site_host(SITE_URL)
    if site_host:
        hosts.append(site_host)

    # Helpful for tests/internal checks even if DEBUG=False
    if TESTING:
        hosts.extend(_local_hosts)

    # Normalize + deduplicate
    normalized_hosts: list[str] = []
    seen_hosts: set[str] = set()
    for h in hosts:
        nh = _normalize_allowed_host(h)
        if not nh:
            continue
        if nh not in seen_hosts:
            normalized_hosts.append(nh)
            seen_hosts.add(nh)

    # Fallback avoids empty list crash
    ALLOWED_HOSTS = normalized_hosts or ["localhost", "127.0.0.1"]

# ===================================
# Installed Apps
# ===================================
INSTALLED_APPS: list[str] = []

# Jazzmin must come before admin when installed
if _module_exists("jazzmin"):
    INSTALLED_APPS.append("jazzmin")

INSTALLED_APPS += [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "whitenoise.runserver_nostatic",
    "django.contrib.staticfiles",
    "django.contrib.messages",
    "django.contrib.humanize",
]

# Optional third-party apps (safe if missing in some environments)
if _module_exists("widget_tweaks"):
    INSTALLED_APPS.append("widget_tweaks")
if _module_exists("django_crontab"):
    INSTALLED_APPS.append("django_crontab")

# Local apps
INSTALLED_APPS += [
    "doctor.apps.DoctorConfig",
    "patient.apps.PatientConfig",
    "accounts",
    "medical_archive",
    "home",
    "appointments",
    "prescription",
    "core",
    "audit",
]

# Optional app(s)
if _module_exists("lab"):
    INSTALLED_APPS.append("lab")

# ===================================
# Middleware
# ===================================
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# ===================================
# URLs / WSGI / ASGI (case-safe)
# ===================================
ROOT_URLCONF = f"{PROJECT_PACKAGE}.urls"
WSGI_APPLICATION = f"{PROJECT_PACKAGE}.wsgi.application"

# Optional ASGI path (safe even if not used directly)
ASGI_APPLICATION = f"{PROJECT_PACKAGE}.asgi.application"

# ===================================
# Templates
# ===================================
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# ===================================
# Database (dj_database_url + local fallback)
# ===================================
fallback_url = (
    f"postgresql://{env_str('DB_USER', 'postgres')}:"
    f"{env_str('DB_PASSWORD', '')}"
    f"@{env_str('DB_HOST', '127.0.0.1')}:"
    f"{env_str('DB_PORT', '5432')}/"
    f"{env_str('DB_NAME', 'clinichub_db')}"
)

# Optional test SQLite fallback (disabled by default)
if TESTING and env_bool("USE_SQLITE_FOR_TESTS", False):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": str(BASE_DIR / "test_db.sqlite3"),
        }
    }
else:
    DATABASE_URL = env_str("DATABASE_URL", fallback_url)
    _db_scheme = (urlparse(DATABASE_URL).scheme or "").lower()
    _db_is_postgres = _db_scheme.startswith("postgres")

    DATABASES = {
        "default": dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=env_int("DB_CONN_MAX_AGE", 600),
            ssl_require=(not DEBUG and _db_is_postgres and not TESTING),
        )
    }

    # Enforce SSL for postgres in production
    if not DEBUG and _db_is_postgres and not TESTING:
        DATABASES["default"].setdefault("OPTIONS", {})
        DATABASES["default"]["OPTIONS"]["sslmode"] = "require"

# Optional DB behavior
if env_bool("DB_ATOMIC_REQUESTS", False):
    DATABASES["default"]["ATOMIC_REQUESTS"] = True

# ===================================
# Password validation
# ===================================
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {"min_length": env_int("PASSWORD_MIN_LENGTH", 8)},
    },
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ===================================
# I18N / Timezone
# ===================================
LANGUAGE_CODE = env_str("LANGUAGE_CODE", "en-us")

# Default clinic timezone (Baghdad)
CLINIC_TZ = env_str("CLINIC_TZ", "Asia/Baghdad")
TIME_ZONE = env_str("TIME_ZONE", CLINIC_TZ)

USE_I18N = True
USE_TZ = True

# ===================================
# Static / Media (Django 5+ STORAGES)
# ===================================
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS: list[Path] = []
_static_dir = BASE_DIR / "static"
if _static_dir.exists():
    STATICFILES_DIRS.append(_static_dir)

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

if DEBUG:
    STORAGES = {
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    }
else:
    STORAGES = {
        "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    }

# Optional WhiteNoise tuning
WHITENOISE_AUTOREFRESH = DEBUG
WHITENOISE_USE_FINDERS = DEBUG
WHITENOISE_MAX_AGE = env_int("WHITENOISE_MAX_AGE", 31536000 if not DEBUG else 0)

# Optional flag used by urls.py for dev-like media serving
SERVE_MEDIA = env_bool("SERVE_MEDIA", False)

# ===================================
# Auth
# ===================================
AUTH_USER_MODEL = "accounts.User"

LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/accounts/login/"

# ===================================
# Messages (Bootstrap mapping)
# ===================================
MESSAGE_TAGS = {
    messages.DEBUG: "secondary",
    messages.INFO: "info",
    messages.SUCCESS: "success",
    messages.WARNING: "warning",
    messages.ERROR: "danger",
}

# ===================================
# Primary Key
# ===================================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ===================================
# Email
# ===================================
if DEBUG:
    EMAIL_BACKEND = env_str("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
else:
    EMAIL_BACKEND = env_str("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")

EMAIL_HOST = env_str("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = env_int("EMAIL_PORT", 587)
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", True)
EMAIL_USE_SSL = env_bool("EMAIL_USE_SSL", False)

# Prevent invalid TLS+SSL combo
if EMAIL_USE_TLS and EMAIL_USE_SSL:
    EMAIL_USE_SSL = False

EMAIL_HOST_USER = env_str("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = env_str("EMAIL_HOST_PASSWORD", "")

DEFAULT_FROM_EMAIL = env_str("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER or "noreply@clinichub.local")
SERVER_EMAIL = env_str("SERVER_EMAIL", DEFAULT_FROM_EMAIL)
ADMIN_EMAIL = env_str("ADMIN_EMAIL", "ops@example.com")

# ===================================
# Twilio (optional)
# ===================================
TWILIO_ACCOUNT_SID = env_str("TWILIO_ACCOUNT_SID", "")
TWILIO_AUTH_TOKEN = env_str("TWILIO_AUTH_TOKEN", "")
TWILIO_PHONE_NUMBER = env_str("TWILIO_PHONE_NUMBER", "+10000000000")

# ===================================
# Jazzmin
# ===================================
JAZZMIN_SETTINGS = {
    "site_title": "Clinic Admin",
    "site_header": "Clinic Management System",
    "site_brand": "ClinicHub",
    "welcome_sign": "Welcome to the Clinic Admin Dashboard",
    "search_model": ["patient.Patient", "doctor.Doctor"],
    "topmenu_links": [
        {"name": "Home", "url": "admin:index"},
        {"app": "patient"},
        {"app": "doctor"},
        {"app": "appointments"},
        {"app": "prescription"},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "icons": {
        "accounts.User": "fas fa-user",
        "auth.Group": "fas fa-users",
        "patient.Patient": "fas fa-user-injured",
        "doctor.Doctor": "fas fa-user-md",
        "appointments.Appointment": "fas fa-calendar-check",
        "prescription.Prescription": "fas fa-file-medical",
    },
    "default_icon_parents": "fas fa-clinic-medical",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
}

JAZZMIN_UI_TWEAKS = {
    "theme": "materia",
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "sidebar": "sidebar-dark-primary",
    "actions_sticky_top": True,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-outline-info",
        "warning": "btn-outline-warning",
        "danger": "btn-outline-danger",
        "success": "btn-outline-success",
    },
    "rounded_corners": True,
    "hover_effects": True,
    "dark_mode_theme": None,
}

# ===================================
# Project-specific defaults
# ===================================
APPOINTMENT_DURATION_MINUTES = env_int("APPOINTMENT_DURATION_MINUTES", 15)

# Queue / public display / booking behavior (used in appointments.views)
QUEUE_USE_CALLED_STATUS = env_bool("QUEUE_USE_CALLED_STATUS", False)
QUEUE_PUBLIC_REQUIRE_TOKEN = env_bool("QUEUE_PUBLIC_REQUIRE_TOKEN", False)
QUEUE_PUBLIC_TOKEN = env_str("QUEUE_PUBLIC_TOKEN", "")
QUEUE_PUBLIC_SHOW_PATIENT_NAME = env_bool("QUEUE_PUBLIC_SHOW_PATIENT_NAME", False)  # keep PHI hidden by default
QUEUE_PUBLIC_INCLUDE_IDS = env_bool("QUEUE_PUBLIC_INCLUDE_IDS", False)
QUEUE_DISPLAY_DOCTORS_LIMIT = env_int("QUEUE_DISPLAY_DOCTORS_LIMIT", 0) or None

BOOKING_REQUEST_BLOCK_CONFLICTS = env_bool("BOOKING_REQUEST_BLOCK_CONFLICTS", True)
STRICT_SECRETARY_SCOPE = env_bool("STRICT_SECRETARY_SCOPE", False)

# Demo / feature flags (optional, helpful across builds)
DEMO_MODE = env_bool("DEMO_MODE", False)

# ===================================
# AI / ML (Diabetes Prediction)
# ===================================
DIABETES_MODEL_DIR = BASE_DIR / "ml" / "artifacts"

DIABETES_MODEL_FILENAME = env_str(
    "DIABETES_MODEL_FILENAME",
    "diabetes_binary_RF_base_diabetes_multiclass.joblib",
)

DIABETES_MODEL_NAME = env_str(
    "DIABETES_MODEL_NAME",
    "binary_RF_base_diabetes_multiclass",
)

_raw_model_path = env_str("DIABETES_MODEL_PATH", "")
DIABETES_MODEL_PATH = _raw_model_path or None

DIABETES_OVERWRITE_STATUS = env_bool("DIABETES_OVERWRITE_STATUS", False)
DIABETES_RISK_MEDIUM = env_float("DIABETES_RISK_MEDIUM", 0.212)
DIABETES_RISK_HIGH = env_float("DIABETES_RISK_HIGH", 0.35)

# ===================================
# Security (CSRF / cookies / HTTPS)
# ===================================
raw_csrf_origins = env_str("CSRF_TRUSTED_ORIGINS", "")
if raw_csrf_origins:
    CSRF_TRUSTED_ORIGINS = [x.strip() for x in raw_csrf_origins.split(",") if x.strip()]
else:
    CSRF_TRUSTED_ORIGINS = _build_csrf_trusted_origins(ALLOWED_HOSTS, SITE_URL)

SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_HTTPONLY = True
# Leave CSRF_COOKIE_HTTPONLY default False (many JS flows read CSRF cookie)

X_FRAME_OPTIONS = "DENY"

if not DEBUG and not TESTING:
    # Render / reverse proxy support
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = env_bool("USE_X_FORWARDED_HOST", True)

    SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", True)
    SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", True)
    CSRF_COOKIE_SECURE = env_bool("CSRF_COOKIE_SECURE", True)

    SECURE_HSTS_SECONDS = env_int("SECURE_HSTS_SECONDS", 60 * 60 * 24 * 90)  # 90 days
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", True)
    SECURE_HSTS_PRELOAD = env_bool("SECURE_HSTS_PRELOAD", False)

    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = env_str("SECURE_REFERRER_POLICY", "strict-origin-when-cross-origin")
    SECURE_CROSS_ORIGIN_OPENER_POLICY = env_str("SECURE_CROSS_ORIGIN_OPENER_POLICY", "same-origin")
else:
    # Safer local defaults without forcing HTTPS
    SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", False)
    CSRF_COOKIE_SECURE = env_bool("CSRF_COOKIE_SECURE", False)

# ===================================
# Logging
# ===================================
LOG_LEVEL = env_str("LOG_LEVEL", "DEBUG" if DEBUG else "INFO").upper()
DJANGO_LOG_LEVEL = env_str("DJANGO_LOG_LEVEL", "INFO").upper()
DB_LOGGING = env_bool("DB_LOGGING", False)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            "format": "[{levelname}] {name}: {message}",
            "style": "{",
        },
        "verbose": {
            "format": "{asctime} [{levelname}] {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose" if not DEBUG else "simple",
        }
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },
        "django.utils.autoreload": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "django.db.backends": {
            "handlers": ["console"],
            "level": "DEBUG" if DB_LOGGING else "WARNING",
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
}