"""
Django settings for ClinicHub project.
Generated by 'django-admin startproject' using Django 5.2.1.
"""

import os
from pathlib import Path
from urllib.parse import urlparse

from django.contrib.messages import constants as messages
from django.core.exceptions import ImproperlyConfigured
from decouple import config
import dj_database_url

# -----------------------------------
# Paths
# -----------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# -----------------------------------
# Core / Debug
# -----------------------------------
SECRET_KEY = config("SECRET_KEY")

# IMPORTANT: default to False for safety
DEBUG = config("DEBUG", default="False").lower() in ("true", "1", "yes")

if not DEBUG:
    _secret_key = SECRET_KEY.strip()
    _unsafe_secret_markers = {
        "change-me",
        "changeme",
        "generate_a_new_strong_production_secret_key",
        "replace_with_new_django_secret_key",
        "secret",
    }
    if (
        not _secret_key
        or _secret_key.lower().startswith("django-insecure-")
        or _secret_key.lower() in _unsafe_secret_markers
        or len(_secret_key) < 50
        or len(set(_secret_key)) < 5
    ):
        raise ImproperlyConfigured(
            "Production SECRET_KEY is missing or unsafe."
        )

# Keep trailing slash behavior (recommended in Django)
APPEND_SLASH = True


def _host_from_url(url: str) -> str:
    """
    Extract host from SITE_URL safely.
    """
    try:
        netloc = urlparse(url).netloc
        return netloc.split(":")[0] if netloc else ""
    except Exception:
        return ""


# Public base URL for absolute links (emails, WhatsApp deep-links, etc.)
SITE_URL = config("SITE_URL", default="https://clinichub.onrender.com").rstrip("/")
SITE_HOST = _host_from_url(SITE_URL)

# Resolve hosts:
# - DEV: keep it safe (localhost only)
# - PROD: prefer ALLOWED_HOSTS from env; fallback to RENDER_EXTERNAL_HOSTNAME; then SITE_URL host
if DEBUG:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", "[::1]"]
else:
    render_host = config("RENDER_EXTERNAL_HOSTNAME", default="").strip()
    env_hosts = [h.strip() for h in config("ALLOWED_HOSTS", default="").split(",") if h.strip()]
    fallback_hosts = [h for h in [render_host, SITE_HOST] if h]
    ALLOWED_HOSTS = env_hosts or fallback_hosts

# -----------------------------------
# Installed Apps
# -----------------------------------
INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",

    # WhiteNoise dev helper before staticfiles (so dev server doesn’t serve its own static)
    "whitenoise.runserver_nostatic",
    "django.contrib.staticfiles",

    "django.contrib.messages",
    "django.contrib.humanize",

    "widget_tweaks",
    "django_crontab",

    # Local apps
    "doctor.apps.DoctorConfig",
    "patient.apps.PatientConfig",
    "accounts",
    "medical_archive",
    "home",
    "appointments",
    "prescription",
    "lab",
    "core",
    "hospital",
    "pharmacy",
    "licensing.apps.LicensingConfig",
    "analytics.apps.AnalyticsConfig",
]

# -----------------------------------
# Middleware
# -----------------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # static files in prod
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "licensing.middleware.LicenseEnforcementMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# -----------------------------------
# URLs / WSGI
# -----------------------------------
ROOT_URLCONF = "ClinicHub.urls"
WSGI_APPLICATION = "ClinicHub.wsgi.application"

# -----------------------------------
# Templates
# -----------------------------------
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "licensing.context_processors.licensing_context",
            ],
        },
    },
]

# -----------------------------------
# Database (unified via dj_database_url with fallback to DB_* vars)
# -----------------------------------
fallback_url = (
    f"postgres://{config('DB_USER', default='postgres')}:"
    f"{config('DB_PASSWORD', default='')}"
    f"@{config('DB_HOST', default='127.0.0.1')}:"
    f"{config('DB_PORT', default='5432')}/"
    f"{config('DB_NAME', default='clinichub_db')}"
)

DATABASES = {
    "default": dj_database_url.config(
        default=config("DATABASE_URL", default=fallback_url),
        conn_max_age=600,       # persistent connections
        ssl_require=not DEBUG,  # require SSL in production
    )
}

if not DEBUG:
    _database = DATABASES["default"]
    _database_markers = {
        "production_database_name",
        "production_database_user",
        "production_database_password",
        "production_database_host",
        "production_database_port",
        "user",
        "password",
        "host",
        "port",
        "dbname",
    }
    _database_values = (
        str(_database.get("NAME") or "").strip().lower(),
        str(_database.get("USER") or "").strip().lower(),
        str(_database.get("HOST") or "").strip().lower(),
        str(_database.get("PORT") or "").strip().lower(),
    )
    if (
        not _database.get("NAME")
        or not _database.get("HOST")
        or not _database.get("PORT")
        or any(value in _database_markers for value in _database_values)
    ):
        raise ImproperlyConfigured(
            "Production database configuration is missing or unsafe."
        )

if not DEBUG:
    DATABASES["default"].setdefault("OPTIONS", {})
    DATABASES["default"]["OPTIONS"]["sslmode"] = "require"

# -----------------------------------
# Password validation
# -----------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator", "OPTIONS": {"min_length": 8}},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# -----------------------------------
# I18N / Timezone
# -----------------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Baghdad"
USE_I18N = True
USE_TZ = True

# Domain logic timezone (used by your app where needed)
CLINIC_TZ = config("CLINIC_TZ", default="Asia/Baghdad")

# -----------------------------------
# Static / Media (WhiteNoise; Django 5+ STORAGES)
# -----------------------------------
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

if DEBUG:
    STORAGES = {
        "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    }
else:
    STORAGES = {
        "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    }

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Confidential clinical files are kept outside public MEDIA_ROOT.
PRIVATE_MEDIA_ROOT = BASE_DIR / "private_media"

# -----------------------------------
# Auth
# -----------------------------------
AUTH_USER_MODEL = "accounts.User"
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/accounts/login/"

# -----------------------------------
# Messages (Bootstrap mapping)
# -----------------------------------
MESSAGE_TAGS = {
    messages.DEBUG: "secondary",
    messages.INFO: "info",
    messages.SUCCESS: "success",
    messages.WARNING: "warning",
    messages.ERROR: "danger",
}

# -----------------------------------
# Primary Key
# -----------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# -----------------------------------
# Email (FIXED: password reset will actually send when SMTP creds exist)
# -----------------------------------
# ✅ By default: SMTP in BOTH dev & prod (so "Forgot password" can deliver).
# ✅ If you want dev console printing instead, set:
#    EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
EMAIL_BACKEND = config(
    "EMAIL_BACKEND",
    default="django.core.mail.backends.smtp.EmailBackend",
).strip()

EMAIL_HOST = config("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = int(config("EMAIL_PORT", default="587"))
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default="True").lower() in ("true", "1", "yes")
EMAIL_USE_SSL = config("EMAIL_USE_SSL", default="False").lower() in ("true", "1", "yes")
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")

# Optional quality-of-life
EMAIL_TIMEOUT = int(config("EMAIL_TIMEOUT", default="15"))

# Sender defaults
DEFAULT_FROM_EMAIL = config(
    "DEFAULT_FROM_EMAIL",
    default=(EMAIL_HOST_USER or "no-reply@localhost"),
)
ADMIN_EMAIL = config("ADMIN_EMAIL", default="ops@example.com")

# Optional: make reset tokens valid for longer/shorter (seconds)
# PASSWORD_RESET_TIMEOUT = int(config("PASSWORD_RESET_TIMEOUT", default=str(60 * 60 * 24)))  # 1 day

# -----------------------------------
# Twilio (optional)
# -----------------------------------
TWILIO_ACCOUNT_SID = config("TWILIO_ACCOUNT_SID", default="")
TWILIO_AUTH_TOKEN = config("TWILIO_AUTH_TOKEN", default="")
TWILIO_PHONE_NUMBER = config("TWILIO_PHONE_NUMBER", default="+10000000000")

# -----------------------------------
# Jazzmin
# -----------------------------------
JAZZMIN_SETTINGS = {
    "site_title": "Clinic Admin",
    "site_header": "Clinic Management System",
    "site_brand": "ClinicHub",
    "welcome_sign": "Welcome to the Clinic Admin Dashboard",
    "search_model": ["patient.Patient", "doctor.Doctor"],
    "topmenu_links": [
        {"name": "Home", "url": "admin:index"},
        {"app": "patient"},
        {"app": "doctor"},
        {"app": "appointments"},
        {"app": "prescription"},
        # {"app": "medical_archive"},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "icons": {
        "accounts.User": "fas fa-user",
        "auth.Group": "fas fa-users",
        "patient.Patient": "fas fa-user-injured",
        "doctor.Doctor": "fas fa-user-md",
        "appointments.Appointment": "fas fa-calendar-check",
        "prescription.Prescription": "fas fa-file-medical",
    },
    "default_icon_parents": "fas fa-clinic-medical",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
}

JAZZMIN_UI_TWEAKS = {
    "theme": "materia",
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "sidebar": "sidebar-dark-primary",
    "actions_sticky_top": True,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-outline-info",
        "warning": "btn-outline-warning",
        "danger": "btn-outline-danger",
        "success": "btn-outline-success",
    },
    "rounded_corners": True,
    "hover_effects": True,
    "dark_mode_theme": None,
}

# -----------------------------------
# Project-specific defaults
# -----------------------------------
APPOINTMENT_DURATION_MINUTES = int(config("APPOINTMENT_DURATION_MINUTES", default="15"))

# -----------------------------------
# AI / ML (Diabetes Prediction)
# -----------------------------------
DIABETES_MODEL_DIR = BASE_DIR / "ml" / "artifacts"

DIABETES_MODEL_FILENAME = config(
    "DIABETES_MODEL_FILENAME",
    default="diabetes_binary_RF_base_diabetes_multiclass.joblib",
).strip()

DIABETES_MODEL_NAME = config("DIABETES_MODEL_NAME", default="binary_RF_base_diabetes_multiclass").strip()

_raw_model_path = config("DIABETES_MODEL_PATH", default="").strip()
DIABETES_MODEL_PATH = _raw_model_path if _raw_model_path else None

DIABETES_OVERWRITE_STATUS = config("DIABETES_OVERWRITE_STATUS", default="False").lower() in ("true", "1", "yes")
DIABETES_RISK_MEDIUM = float(config("DIABETES_RISK_MEDIUM", default="0.212"))
DIABETES_RISK_HIGH = float(config("DIABETES_RISK_HIGH", default="0.35"))

# -----------------------------------
# Security helpers
# -----------------------------------
def _build_csrf_trusted_from_hosts(hosts):
    """
    Convert ALLOWED_HOSTS into CSRF_TRUSTED_ORIGINS (https://host).
    For localhost/127.0.0.1 include http as well to ease dev behind proxies.
    """
    origins = []
    for h in hosts:
        h = (h or "").strip()
        if not h:
            continue
        if h in ("127.0.0.1", "localhost"):
            origins.append(f"http://{h}")
            origins.append(f"https://{h}")
        else:
            origins.append(f"https://{h}")
    return origins

# -----------------------------------
# Security (Production)
# -----------------------------------
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    CSRF_TRUSTED_ORIGINS = _build_csrf_trusted_from_hosts(ALLOWED_HOSTS)

    SECURE_SSL_REDIRECT = config("SECURE_SSL_REDIRECT", default="True").lower() in ("true", "1", "yes")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 90
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = False

    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
    X_FRAME_OPTIONS = "DENY"
    SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"
else:
    raw_csrf = config("CSRF_TRUSTED_ORIGINS", default="").strip()
    if raw_csrf:
        CSRF_TRUSTED_ORIGINS = [x.strip() for x in raw_csrf.split(",") if x.strip()]

SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_HTTPONLY = True

# -----------------------------------
# Logging (reduced noise in dev autoreload)
# -----------------------------------
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "loggers": {
        "django": {"handlers": ["console"], "level": "INFO"},
        "django.utils.autoreload": {"handlers": ["console"], "level": "WARNING", "propagate": False},
    },
    "root": {"handlers": ["console"], "level": "DEBUG" if DEBUG else "INFO"},
}

# -----------------------------------
# ClinicHub Licensing
# -----------------------------------
LICENSE_PRODUCT_CODE = "clinichub"

LICENSE_INSTALLATION_NAME = os.getenv(
    "LICENSE_INSTALLATION_NAME",
    "ClinicHub Installation",
)

# Only the public verification key is stored with the installed system.
# Never copy the owner's private key into a customer installation.
LICENSE_PUBLIC_KEY_FILE = (
    BASE_DIR / "licensing_keys" / "clinichub_public_key.pem"
)

# Keep enforcement disabled during initial installation. Enable it only after
# a valid license has been installed and license_status reports Allowed: yes.
LICENSE_ENFORCEMENT_ENABLED = (
    os.getenv("LICENSE_ENFORCEMENT_ENABLED", "0").strip().lower()
    in {"1", "true", "yes", "on"}
)

# Optional online validation. Leave both values empty when using signed
# offline licenses.
LICENSE_SERVER_URL = os.getenv("LICENSE_SERVER_URL", "").strip()
LICENSE_SERVER_API_KEY = os.getenv("LICENSE_SERVER_API_KEY", "").strip()
LICENSE_ONLINE_TIMEOUT = int(
    os.getenv("LICENSE_ONLINE_TIMEOUT", "5")
)
LICENSE_ONLINE_CHECK_HOURS = int(
    os.getenv("LICENSE_ONLINE_CHECK_HOURS", "24")
)

# These routes remain available before activation so that administrators can
# sign in and install or inspect the license.
LICENSE_BYPASS_PATH_PREFIXES = (
    "/accounts/",
    "/licensing/",
)

# Map application URL prefixes to the module names stored in signed licenses.
LICENSE_MODULE_PATHS = {
    "/doctor/": "doctor",
    "/patient/": "patient",
    "/appointments/": "appointments",
    "/prescription/": "prescription",
    "/lab/": "lab",
    "/pharmacy/": "pharmacy",
    "/archive/": "medical_archive",
}