# Generated by Django 5.2.4 on 2026-09-20 07:54

import core.private_storage
import django.db.models.deletion
import django.utils.timezone
import ecg.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0007_notification_action_url_and_more'),
        ('doctor', '0016_private_clinical_storage_signature'),
        ('hospital', '0002_staffassignment'),
        ('patient', '0003_alter_patient_mobile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ECGRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('device_manufacturer', models.CharField(blank=True, max_length=120)),
                ('device_model', models.CharField(blank=True, max_length=120)),
                ('sampling_frequency_hz', models.PositiveIntegerField(blank=True, null=True)),
                ('lead_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('workflow_status', models.CharField(choices=[('uploaded', 'Uploaded'), ('ready', 'Ready for analysis'), ('analyzing', 'Analyzing'), ('analyzed', 'Analyzed'), ('reviewed', 'Reviewed by physician'), ('failed', 'Processing failed')], db_index=True, default='uploaded', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecg_records', to='appointments.appointment')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ecg_records', to='hospital.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ecg_records', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ecg_records', to='hospital.department')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecg_records', to='doctor.doctor')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ecg_records', to='hospital.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecg_records', to='patient.patient')),
            ],
            options={
                'ordering': ['-recorded_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ECGFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=core.private_storage.PrivateClinicalStorage(), upload_to=ecg.models.ecg_file_upload_to)),
                ('kind', models.CharField(choices=[('raw_signal', 'Raw ECG signal'), ('report_pdf', 'ECG report PDF'), ('image', 'ECG image'), ('xml', 'XML'), ('dicom', 'DICOM'), ('wfdb', 'WFDB'), ('csv', 'CSV'), ('other', 'Other')], db_index=True, default='raw_signal', max_length=20)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='ecg.ecgrecord')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddIndex(
            model_name='ecgrecord',
            index=models.Index(fields=['patient', 'recorded_at'], name='ecg_patient_recorded_idx'),
        ),
        migrations.AddIndex(
            model_name='ecgrecord',
            index=models.Index(fields=['doctor', 'recorded_at'], name='ecg_doctor_recorded_idx'),
        ),
    ]
