# Generated by Django 5.2.4 on 2026-10-07 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg', '0001_initial'),
        ('medical_archive', '0008_alter_archiveattachment_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecgfile',
            name='source_archive_attachment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_ecg_file', to='medical_archive.archiveattachment'),
        ),
    ]
