# Generated by Django 5.2.4 on 2026-07-17 14:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0002_staffassignment'),
        ('prescription', '0005_prescription_patient_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=50)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('generic_name', models.CharField(db_index=True, max_length=200)),
                ('brand_name', models.CharField(blank=True, db_index=True, max_length=200)),
                ('strength', models.CharField(blank=True, max_length=100)),
                ('dosage_form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('suspension', 'Suspension'), ('injection', 'Injection'), ('cream', 'Cream'), ('ointment', 'Ointment'), ('drops', 'Drops'), ('inhaler', 'Inhaler'), ('suppository', 'Suppository'), ('other', 'Other')], db_index=True, default='tablet', max_length=20)),
                ('dispensing_unit', models.CharField(default='unit', help_text='Examples: tablet, capsule, bottle, vial, tube.', max_length=30)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('requires_prescription', models.BooleanField(default=True)),
                ('is_controlled', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='hospital.hospital')),
            ],
            options={
                'ordering': ['generic_name', 'brand_name', 'strength'],
            },
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=30)),
                ('pharmacy_type', models.CharField(choices=[('outpatient', 'Outpatient'), ('inpatient', 'Inpatient'), ('emergency', 'Emergency'), ('central', 'Central')], db_index=True, default='outpatient', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pharmacies', to='hospital.branch')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['branch_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reorder_level', models.PositiveIntegerField(default=0)),
                ('target_stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_inventory', to='pharmacy.medicine')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='pharmacy.pharmacy')),
            ],
            options={
                'ordering': ['pharmacy_id', 'medicine__generic_name'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('partial', 'Partially Dispensed'), ('dispensed', 'Dispensed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='sent', max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('stat', 'STAT')], db_index=True, default='normal', max_length=10)),
                ('doctor_notes', models.TextField(blank=True)),
                ('pharmacy_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='pharmacy.pharmacy')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_orders', to='prescription.prescription')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_orders_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', 'sent_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('medication_name', models.CharField(blank=True, max_length=200)),
                ('dosage', models.CharField(blank=True, max_length=255)),
                ('requested_quantity', models.PositiveIntegerField(default=1)),
                ('requested_unit', models.CharField(default='unit', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('available', 'Available'), ('unavailable', 'Unavailable'), ('partial', 'Partially Available'), ('dispensed', 'Dispensed'), ('substituted', 'Substituted')], db_index=True, default='pending', max_length=20)),
                ('is_substitution', models.BooleanField(default=False)),
                ('pharmacist_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='pharmacy.medicine')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='pharmacy.pharmacyorder')),
                ('prescription_medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_order_items', to='prescription.medication')),
            ],
            options={
                'ordering': ['order_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyStaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_manager', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_assignments', to='pharmacy.pharmacy')),
                ('staff_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_assignments', to='hospital.staffassignment')),
            ],
            options={
                'ordering': ['pharmacy_id', 'staff_assignment_id'],
            },
        ),
        migrations.AddField(
            model_name='pharmacyorder',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_orders', to='pharmacy.pharmacystaffassignment'),
        ),
        migrations.CreateModel(
            name='Dispense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('voided', 'Voided')], db_index=True, default='draft', max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True)),
                ('dispensed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispenses', to='pharmacy.pharmacyorder')),
                ('dispensed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispenses', to='pharmacy.pharmacystaffassignment')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('batch_number', models.CharField(max_length=100)),
                ('expiry_date', models.DateField(db_index=True)),
                ('received_quantity', models.PositiveIntegerField(default=0)),
                ('quantity_on_hand', models.PositiveIntegerField(default=0)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('selling_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('supplier_name', models.CharField(blank=True, max_length=200)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='pharmacy.pharmacyinventory')),
            ],
            options={
                'ordering': ['expiry_date', 'received_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DispenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('dispense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='pharmacy.dispense')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispense_items', to='pharmacy.pharmacyorderitem')),
                ('stock_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispense_items', to='pharmacy.stockbatch')),
            ],
            options={
                'ordering': ['dispense_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('receipt', 'Receipt'), ('dispense', 'Dispense'), ('patient_return', 'Patient Return'), ('supplier_return', 'Supplier Return'), ('adjustment_in', 'Adjustment In'), ('adjustment_out', 'Adjustment Out'), ('expired', 'Expired'), ('damaged', 'Damaged')], db_index=True, max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('balance_before', models.PositiveIntegerField()),
                ('balance_after', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_stock_movements', to=settings.AUTH_USER_MODEL)),
                ('dispense_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='pharmacy.dispenseitem')),
                ('stock_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='pharmacy.stockbatch')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['hospital', 'is_active'], name='med_hospital_active_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['generic_name', 'brand_name'], name='med_names_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('hospital', 'code'), name='uq_medicine_hospital_code'),
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('barcode', ''), _negated=True)), fields=('hospital', 'barcode'), name='uq_medicine_hosp_barcode'),
        ),
        migrations.AddIndex(
            model_name='pharmacy',
            index=models.Index(fields=['branch', 'is_active'], name='pharm_branch_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='pharmacy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('branch', 'code'), name='uq_pharmacy_branch_code'),
        ),
        migrations.AddIndex(
            model_name='pharmacyinventory',
            index=models.Index(fields=['pharmacy', 'is_active'], name='inventory_pharm_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='pharmacyinventory',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('pharmacy', 'medicine'), name='uq_pharmacy_inventory'),
        ),
        migrations.AddIndex(
            model_name='pharmacyorderitem',
            index=models.Index(fields=['order', 'status'], name='order_item_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='pharmacyorderitem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('order', 'prescription_medication'), name='uq_order_prescription_med'),
        ),
        migrations.AddConstraint(
            model_name='pharmacyorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('requested_quantity__gt', 0)), name='ck_order_item_quantity_pos'),
        ),
        migrations.AddIndex(
            model_name='pharmacystaffassignment',
            index=models.Index(fields=['pharmacy', 'is_active'], name='pharm_staff_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='pharmacystaffassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('pharmacy', 'staff_assignment'), name='uq_pharmacy_staff'),
        ),
        migrations.AddIndex(
            model_name='pharmacyorder',
            index=models.Index(fields=['pharmacy', 'status', 'sent_at'], name='order_pharm_status_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyorder',
            index=models.Index(fields=['prescription', 'status'], name='order_rx_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='pharmacyorder',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('status__in', ['sent', 'accepted', 'in_progress', 'partial'])), fields=('prescription',), name='uq_active_prescription_order'),
        ),
        migrations.AddIndex(
            model_name='dispense',
            index=models.Index(fields=['order', 'status'], name='dispense_order_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='dispense',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='ck_dispense_total_nonneg'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['inventory', 'expiry_date', 'is_active'], name='batch_inventory_exp_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('inventory', 'batch_number'), name='uq_inventory_batch_number'),
        ),
        migrations.AddConstraint(
            model_name='stockbatch',
            constraint=models.CheckConstraint(condition=models.Q(('received_quantity__gte', 0)), name='ck_batch_received_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='stockbatch',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_on_hand__gte', 0)), name='ck_batch_on_hand_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='stockbatch',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_price__gte', 0)), name='ck_batch_purchase_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='stockbatch',
            constraint=models.CheckConstraint(condition=models.Q(('selling_price__gte', 0)), name='ck_batch_selling_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='dispenseitem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('dispense', 'order_item', 'stock_batch'), name='uq_dispense_item_batch'),
        ),
        migrations.AddConstraint(
            model_name='dispenseitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_dispense_item_quantity_pos'),
        ),
        migrations.AddConstraint(
            model_name='dispenseitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='ck_dispense_item_price_nonneg'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['stock_batch', 'created_at'], name='stock_move_batch_date_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', 'created_at'], name='stock_move_type_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_stock_move_quantity_pos'),
        ),
    ]
