# Generated by Django 5.2.4 on 2026-07-19 16:21

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispense',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='dispense',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispense',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('insurance', 'Insurance'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='dispense',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid')], db_index=True, default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='dispense',
            name='received_by_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='dispense',
            name='transaction_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='dispense',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='dispense',
            index=models.Index(fields=['payment_status', 'created_at'], name='dispense_payment_idx'),
        ),
        migrations.AddConstraint(
            model_name='dispense',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__gte', 0)), name='ck_dispense_paid_nonneg'),
        ),
    ]
