# Generated by Django 5.2.4 on 2026-07-24 12:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_staffassignment'),
        ('pharmacy', '0002_dispense_amount_paid_dispense_paid_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacySale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, default='', max_length=200)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('voided', 'Voided')], db_index=True, default='draft', max_length=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid')], db_index=True, default='unpaid', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('insurance', 'Insurance'), ('other', 'Other')], default='', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PharmacySaleAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sale_item_id', 'stock_batch__expiry_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PharmacySaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sale_id', 'id'],
            },
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='operating_mode',
            field=models.CharField(choices=[('integrated', 'Integrated with Hospital'), ('standalone', 'Standalone Pharmacy')], db_index=True, default='integrated', help_text='Integrated pharmacies receive hospital prescriptions. Standalone pharmacies use direct POS sales and a system-managed administrative branch.', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('dispense', 'Dispense'), ('direct_sale', 'Direct Sale'), ('patient_return', 'Patient Return'), ('supplier_return', 'Supplier Return'), ('adjustment_in', 'Adjustment In'), ('adjustment_out', 'Adjustment Out'), ('expired', 'Expired'), ('damaged', 'Damaged')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='pharmacy',
            index=models.Index(fields=['operating_mode', 'is_active'], name='pharm_mode_active_idx'),
        ),
        migrations.AddField(
            model_name='pharmacysale',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direct_sales', to='pharmacy.pharmacystaffassignment'),
        ),
        migrations.AddField(
            model_name='pharmacysale',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pharmacysale',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direct_sales', to='pharmacy.pharmacy'),
        ),
        migrations.AddField(
            model_name='pharmacysale',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_sales_voided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pharmacysaleallocation',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pharmacysaleallocation',
            name='stock_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direct_sale_allocations', to='pharmacy.stockbatch'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='direct_sale_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='pharmacy.pharmacysaleallocation'),
        ),
        migrations.AddField(
            model_name='pharmacysaleitem',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pharmacysaleitem',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direct_sale_items', to='pharmacy.medicine'),
        ),
        migrations.AddField(
            model_name='pharmacysaleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='pharmacy.pharmacysale'),
        ),
        migrations.AddField(
            model_name='pharmacysaleallocation',
            name='sale_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='pharmacy.pharmacysaleitem'),
        ),
        migrations.AddIndex(
            model_name='pharmacysale',
            index=models.Index(fields=['pharmacy', 'status', 'created_at'], name='sale_pharm_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacysale',
            index=models.Index(fields=['payment_status', 'created_at'], name='sale_payment_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='pharmacysale',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='ck_sale_subtotal_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='pharmacysale',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='ck_sale_discount_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='pharmacysale',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='ck_sale_total_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='pharmacysale',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__gte', 0)), name='ck_sale_paid_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='pharmacysale',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__lte', models.F('subtotal'))), name='ck_sale_discount_lte_subtotal'),
        ),
        migrations.AddConstraint(
            model_name='pharmacysale',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__lte', models.F('total_amount'))), name='ck_sale_paid_lte_total'),
        ),
        migrations.AddIndex(
            model_name='pharmacysaleitem',
            index=models.Index(fields=['sale', 'medicine'], name='sale_item_medicine_idx'),
        ),
        migrations.AddConstraint(
            model_name='pharmacysaleitem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('sale', 'medicine'), name='uq_sale_medicine'),
        ),
        migrations.AddConstraint(
            model_name='pharmacysaleitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_sale_item_quantity_pos'),
        ),
        migrations.AddConstraint(
            model_name='pharmacysaleitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='ck_sale_item_price_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='pharmacysaleitem',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='ck_sale_item_discount_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='pharmacysaleallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('sale_item', 'stock_batch'), name='uq_sale_item_batch'),
        ),
        migrations.AddConstraint(
            model_name='pharmacysaleallocation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_sale_alloc_quantity_pos'),
        ),
        migrations.AddConstraint(
            model_name='pharmacysaleallocation',
            constraint=models.CheckConstraint(condition=models.Q(('unit_purchase_price__gte', 0)), name='ck_sale_alloc_cost_nonneg'),
        ),
    ]
