# Generated by Django 5.2.4 on 2025-11-29 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, help_text='If this user is a secretary, link them to their primary doctor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretaries', to='doctor.doctor'),
        ),
    ]
