# Generated by Django 5.2.4 on 2025-11-29 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_assigned_doctor'),
        ('doctor', '0002_alter_doctor_phone_alter_doctor_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, help_text='If this user is a secretary, link them to their primary doctor. For non-secretaries this field will be cleared automatically.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretaries', to='doctor.doctor'),
        ),
    ]
