# Generated by Django 5.2.4 on 2026-01-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_assigned_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Must be approved by admin before logging in (for staff roles).', verbose_name='approved'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('secretary', 'Secretary'), ('lab', 'Lab'), ('patient', 'Patient'), ('admin', 'Admin')], db_index=True, default='patient', help_text='Determines which interface the user can access', max_length=10, verbose_name='role'),
        ),
    ]
