# Generated by Django 5.2.4 on 2026-07-17 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_is_approved_alter_user_role'),
        ('doctor', '0014_doctorvisit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, help_text='If this user is a secretary, link them to their primary doctor. For non-secretaries this field is cleared automatically.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretaries', to='doctor.doctor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Must be approved by admin before logging in for staff roles.', verbose_name='approved'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('secretary', 'Secretary'), ('lab', 'Lab'), ('pharmacist', 'Pharmacist'), ('patient', 'Patient'), ('admin', 'Admin')], db_index=True, default='patient', help_text='Determines which interface the user can access', max_length=10, verbose_name='role'),
        ),
    ]
