# Generated by Django 5.2.4 on 2025-10-22 14:34

import django.core.validators
import django.db.models.deletion
import prescription.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_full_name', models.CharField(help_text="Snapshot of patient's name at time of prescribing", max_length=100, verbose_name='Patient Name')),
                ('age', models.PositiveIntegerField(blank=True, help_text='Patient’s age at time of prescribing (auto-calculated if not provided).', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)], verbose_name='Patient Age')),
                ('instructions', models.TextField(blank=True, null=True, verbose_name='Additional Instructions')),
                ('voice_note', models.FileField(blank=True, null=True, upload_to=prescription.models.voice_upload_to, validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'ogg', 'm4a'])], verbose_name="Doctor's Voice Note")),
                ('doctor_signature', models.ImageField(blank=True, null=True, upload_to=prescription.models.sign_upload_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])], verbose_name='Doctor Signature')),
                ('doctor_logo', models.ImageField(blank=True, null=True, upload_to=prescription.models.logo_upload_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])], verbose_name='Clinic Logo')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=prescription.models.pdf_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Prescription PDF')),
                ('date_issued', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date Issued')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to=prescription.models.qrcode_upload_to, validators=[django.core.validators.FileExtensionValidator(['png'])], verbose_name='QR Code')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('completed', 'Completed'), ('canceled', 'Canceled')], db_index=True, default='draft', max_length=10, verbose_name='Status')),
                ('appointment', models.ForeignKey(help_text='Related appointment from which patient info is derived', on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment', verbose_name='Appointment')),
                ('doctor', models.ForeignKey(help_text='Doctor who issued this prescription', on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='doctor.doctor', verbose_name='Doctor')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'ordering': ['-date_issued'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Medication Name')),
                ('dosage', models.CharField(help_text='Example: 500 mg — 1 tab PO q8h × 5 days', max_length=255, verbose_name='Dosage')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='prescription.prescription')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['doctor', 'date_issued'], name='prescriptio_doctor__ce493e_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['appointment'], name='prescriptio_appoint_2c10b0_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['status'], name='prescriptio_status_716235_idx'),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['prescription'], name='prescriptio_prescri_c6f9e8_idx'),
        ),
    ]
