# Generated by Django 5.2.4 on 2025-12-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_patientbookingrequest_patient_and_more'),
        ('doctor', '0003_doctor_clinic_logo_and_more'),
        ('prescription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='template_key',
            field=models.CharField(blank=True, db_index=True, default='default', help_text='UI template identifier (e.g., dermatology, cardiology).', max_length=50, verbose_name='Template Key'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['template_key'], name='prescriptio_templat_8ce25c_idx'),
        ),
        migrations.AddConstraint(
            model_name='prescription',
            constraint=models.UniqueConstraint(fields=('appointment',), name='unique_prescription_per_appointment'),
        ),
    ]
