# Generated by Django 5.2.4 on 2025-12-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_patientbookingrequest_patient_and_more'),
        ('doctor', '0006_doctor_accent_color_doctor_primary_color_and_more'),
        ('prescription', '0002_prescription_template_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='diagnosis',
            field=models.CharField(blank=True, db_index=True, help_text='Optional. Example: GERD / PCOS / Pelvic pain ...', max_length=255, null=True, verbose_name='Diagnosis (Dx)'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['diagnosis'], name='prescriptio_diagnos_32026e_idx'),
        ),
    ]
