# Generated by Django 5.2.4 on 2025-12-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0003_prescription_diagnosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='diagnosis',
            field=models.CharField(blank=True, db_index=True, help_text='Optional. Example: sore throat, fever, pelvic pain ...', max_length=255, null=True, verbose_name='Diagnosis (Dx)'),
        ),
    ]
