# Generated by Django 5.2.4 on 2026-01-03 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_patientbookingrequest_patient_and_more'),
        ('doctor', '0007_doctor_entity_type_and_more'),
        ('patient', '0001_initial'),
        ('prescription', '0004_alter_prescription_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(blank=True, help_text='Direct link to patient (auto-filled from appointment)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patient.patient', verbose_name='Patient'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', 'date_issued'], name='prescriptio_patient_d7714f_idx'),
        ),
    ]
