# Generated by Django 5.2.4 on 2026-09-17 17:00

import core.private_storage
import django.core.validators
import prescription.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0005_prescription_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='doctor_signature',
            field=models.ImageField(blank=True, null=True, storage=core.private_storage.PrivateClinicalStorage(), upload_to=prescription.models.sign_upload_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])], verbose_name='Doctor Signature'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, storage=core.private_storage.PrivateClinicalStorage(), upload_to=prescription.models.pdf_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Prescription PDF'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, storage=core.private_storage.PrivateClinicalStorage(), upload_to=prescription.models.qrcode_upload_to, validators=[django.core.validators.FileExtensionValidator(['png'])], verbose_name='QR Code'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='voice_note',
            field=models.FileField(blank=True, null=True, storage=core.private_storage.PrivateClinicalStorage(), upload_to=prescription.models.voice_upload_to, validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'ogg', 'm4a'])], verbose_name="Doctor's Voice Note"),
        ),
    ]
