# Generated by Django 5.2.11 on 2026-03-06 17:52

import django.core.validators
import prescription.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0005_prescription_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='voice_note',
            field=models.FileField(blank=True, help_text='Allowed formats: mp3, wav, ogg, m4a, webm', null=True, upload_to=prescription.models.voice_upload_to, validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'ogg', 'm4a', 'webm'])], verbose_name="Doctor's Voice Note"),
        ),
    ]
