# Generated by Django 5.2.4 on 2025-10-22 14:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import medical_archive.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        ('patient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('archive_type', models.CharField(choices=[('visit', 'Visit'), ('lab', 'Lab Result'), ('scan', 'Scan'), ('prescription', 'Prescription'), ('other', 'Other')], default='visit', max_length=50)),
                ('is_critical', models.BooleanField(default=False)),
                ('summary_report', models.TextField(blank=True, help_text='Short summary for fast reports')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final'), ('cancelled', 'Cancelled')], default='final', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archives_created', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_patient_archives', to='doctor.doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_archives', to='patient.patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archives_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient Archive',
                'verbose_name_plural': 'Patient Archives',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArchiveAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=medical_archive.models.archive_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'gif']), medical_archive.models.validate_file_size, medical_archive.models.validate_file_mimetype])),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments_uploaded', to=settings.AUTH_USER_MODEL)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='medical_archive.patientarchive')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='patientarchive',
            constraint=models.UniqueConstraint(fields=('patient', 'doctor', 'title'), name='unique_archive_per_patient_doctor'),
        ),
    ]
