# Generated by Django 5.2.4 on 2025-12-05 14:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import medical_archive.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_patientbookingrequest_patient_and_more'),
        ('doctor', '0002_alter_doctor_phone_alter_doctor_photo'),
        ('medical_archive', '0001_initial'),
        ('patient', '0001_initial'),
        ('prescription', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='patientarchive',
            name='unique_archive_per_patient_doctor',
        ),
        migrations.AddField(
            model_name='patientarchive',
            name='appointment',
            field=models.ForeignKey(blank=True, help_text='Related appointment for this archive (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archives', to='appointments.appointment', verbose_name='Appointment'),
        ),
        migrations.AddField(
            model_name='patientarchive',
            name='prescription',
            field=models.OneToOneField(blank=True, help_text='Linked electronic prescription (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_entry', to='prescription.prescription', verbose_name='Prescription'),
        ),
        migrations.AlterField(
            model_name='archiveattachment',
            name='archive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='medical_archive.patientarchive', verbose_name='Archive'),
        ),
        migrations.AlterField(
            model_name='archiveattachment',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='archiveattachment',
            name='file',
            field=models.FileField(upload_to=medical_archive.models.archive_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'gif']), medical_archive.models.validate_file_size, medical_archive.models.validate_file_mimetype], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='archiveattachment',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At'),
        ),
        migrations.AlterField(
            model_name='archiveattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By'),
        ),
        migrations.AlterField(
            model_name='patientarchive',
            name='archive_type',
            field=models.CharField(choices=[('visit', 'Visit'), ('lab', 'Lab Result'), ('scan', 'Scan'), ('prescription', 'Prescription'), ('other', 'Other')], default='visit', max_length=50, verbose_name='Archive Type'),
        ),
        migrations.AlterField(
            model_name='patientarchive',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='patientarchive',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archives_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='patientarchive',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_patient_archives', to='doctor.doctor', verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='patientarchive',
            name='is_critical',
            field=models.BooleanField(default=False, verbose_name='Is Critical?'),
        ),
        migrations.AlterField(
            model_name='patientarchive',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='patientarchive',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_archives', to='patient.patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='patientarchive',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('final', 'Final'), ('cancelled', 'Cancelled')], default='final', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='patientarchive',
            name='summary_report',
            field=models.TextField(blank=True, help_text='Short summary for fast reports', verbose_name='Summary Report'),
        ),
        migrations.AlterField(
            model_name='patientarchive',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='patientarchive',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='patientarchive',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archives_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddConstraint(
            model_name='patientarchive',
            constraint=models.UniqueConstraint(condition=models.Q(('prescription__isnull', False)), fields=('prescription',), name='unique_archive_per_prescription'),
        ),
    ]
