# Generated by Django 5.2.4 on 2026-01-19 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_archive', '0002_remove_patientarchive_unique_archive_per_patient_doctor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientarchive',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archives_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
    ]
