# Generated by Django 5.2.4 on 2026-01-19 18:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_archive', '0003_alter_patientarchive_created_by'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='patientarchive',
            name='unique_archive_per_prescription',
        ),
        migrations.AlterField(
            model_name='archiveattachment',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Uploaded At'),
        ),
        migrations.AlterField(
            model_name='patientarchive',
            name='archive_type',
            field=models.CharField(choices=[('visit', 'Visit'), ('lab', 'Lab Result'), ('scan', 'Scan'), ('prescription', 'Prescription'), ('other', 'Other')], db_index=True, default='visit', max_length=50, verbose_name='Archive Type'),
        ),
        migrations.AlterField(
            model_name='patientarchive',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='patientarchive',
            name='is_critical',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Critical?'),
        ),
        migrations.AlterField(
            model_name='patientarchive',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('final', 'Final'), ('cancelled', 'Cancelled')], db_index=True, default='final', max_length=20, verbose_name='Status'),
        ),
    ]
