# Generated by Django 5.2.4 on 2026-01-21 05:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import medical_archive.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_archive', '0004_remove_patientarchive_unique_archive_per_prescription_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveVoiceNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(help_text='Doctor voice note (webm/ogg/wav/mp3/m4a).', upload_to=medical_archive.models.archive_voice_path, validators=[django.core.validators.FileExtensionValidator(['webm', 'ogg', 'wav', 'mp3', 'm4a']), medical_archive.models.validate_audio_file_size, medical_archive.models.validate_audio_mimetype], verbose_name='Audio')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration (seconds)')),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Recorded At')),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_notes', to='medical_archive.patientarchive', verbose_name='Archive')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_notes_recorded', to=settings.AUTH_USER_MODEL, verbose_name='Recorded By')),
            ],
            options={
                'verbose_name': 'Voice Note',
                'verbose_name_plural': 'Voice Notes',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
