# Generated by Django 5.2.4 on 2026-01-21 07:36

import django.core.validators
import medical_archive.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_archive', '0005_archivevoicenote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveattachment',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='archivevoicenote',
            name='audio',
            field=models.FileField(help_text='Doctor voice note (webm/ogg/wav/mp3/m4a).', upload_to=medical_archive.models.archive_voice_path, validators=[django.core.validators.FileExtensionValidator(['webm', 'ogg', 'wav', 'mp3', 'm4a', 'aac']), medical_archive.models.validate_audio_file_size, medical_archive.models.validate_audio_mimetype], verbose_name='Audio'),
        ),
    ]
