# Generated by Django 5.2.4 on 2026-01-22 05:30

import django.core.validators
import django.db.models.deletion
import medical_archive.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0014_doctorvisit_and_more'),
        ('medical_archive', '0006_alter_archiveattachment_description_and_more'),
        ('patient', '0003_alter_patient_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveattachment',
            name='file',
            field=models.FileField(upload_to=medical_archive.models.archive_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'gif', 'webp']), medical_archive.models.validate_file_size, medical_archive.models.validate_file_mimetype], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='archivevoicenote',
            name='audio',
            field=models.FileField(help_text='Doctor voice note (webm/ogg/wav/mp3/m4a/aac).', upload_to=medical_archive.models.archive_voice_path, validators=[django.core.validators.FileExtensionValidator(['webm', 'ogg', 'wav', 'mp3', 'm4a', 'aac']), medical_archive.models.validate_audio_file_size, medical_archive.models.validate_audio_mimetype], verbose_name='Audio'),
        ),
        migrations.AlterField(
            model_name='patientarchive',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_patient_archives', to='doctor.doctor', verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='patientarchive',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_archives', to='patient.patient', verbose_name='Patient'),
        ),
    ]
