# Generated by Django 5.2.4 on 2026-08-03 20:24

import django.core.validators
import medical_archive.models
import medical_archive.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_archive', '0007_alter_archiveattachment_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveattachment',
            name='file',
            field=models.FileField(storage=medical_archive.storage.PrivateArchiveStorage(), upload_to=medical_archive.models.archive_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'gif', 'webp']), medical_archive.models.validate_file_size, medical_archive.models.validate_file_mimetype], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='archivevoicenote',
            name='audio',
            field=models.FileField(help_text='Doctor voice note (webm/ogg/wav/mp3/m4a/aac).', storage=medical_archive.storage.PrivateArchiveStorage(), upload_to=medical_archive.models.archive_voice_path, validators=[django.core.validators.FileExtensionValidator(['webm', 'ogg', 'wav', 'mp3', 'm4a', 'aac']), medical_archive.models.validate_audio_file_size, medical_archive.models.validate_audio_mimetype], verbose_name='Audio'),
        ),
    ]
