# Generated by Django 5.2.4 on 2026-01-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='nationality',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True, verbose_name='Nationality'),
        ),
    ]
