# Generated by Django 5.2.4 on 2026-01-11 08:44

import patient.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mobile',
            field=models.CharField(blank=True, db_index=True, help_text='E.164 format: optional +, 7–15 digits (spaces/dashes allowed).', max_length=20, null=True, validators=[patient.models.validate_mobile], verbose_name='Mobile Number'),
        ),
    ]
