# Generated by Django 5.2.4 on 2026-10-02 09:00

from django.db import migrations


class Migration(migrations.Migration):
    """
    Remove legacy soft-delete columns that still exist in the PostgreSQL
    patient_patient table but are no longer part of the current Patient model
    or the current patient migration state.

    Legacy database-only columns:
        - is_deleted
        - deleted_at
        - deleted_by_id

    Django's model state is already correct, so this migration changes only
    the physical database schema.
    """

    dependencies = [
        ("patient", "0003_alter_patient_mobile"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE patient_patient
                            DROP COLUMN IF EXISTS deleted_by_id;

                        ALTER TABLE patient_patient
                            DROP COLUMN IF EXISTS deleted_at;

                        ALTER TABLE patient_patient
                            DROP COLUMN IF EXISTS is_deleted;
                    """,
                    reverse_sql="""
                        ALTER TABLE patient_patient
                            ADD COLUMN is_deleted boolean NOT NULL DEFAULT FALSE;

                        ALTER TABLE patient_patient
                            ALTER COLUMN is_deleted DROP DEFAULT;

                        ALTER TABLE patient_patient
                            ADD COLUMN deleted_at timestamp with time zone NULL;

                        ALTER TABLE patient_patient
                            ADD COLUMN deleted_by_id bigint NULL;

                        ALTER TABLE patient_patient
                            ADD CONSTRAINT patient_patient_deleted_by_id_450e5ef7_fk_accounts_user_id
                            FOREIGN KEY (deleted_by_id)
                            REFERENCES accounts_user(id)
                            DEFERRABLE INITIALLY DEFERRED;

                        CREATE INDEX patient_patient_deleted_by_id_450e5ef7
                            ON patient_patient (deleted_by_id);

                        CREATE INDEX patient_patient_is_deleted_d2f0bb63
                            ON patient_patient (is_deleted);
                    """,
                ),
            ],
            state_operations=[],
        ),
    ]
