# Generated by Django 5.2.11 on 2026-02-23 09:20

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_remove_patient_uniq_patient_mobile_nonempty_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='patient',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
