# Generated by Django 5.2.4 on 2025-10-22 14:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientBookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('contact_info', models.CharField(max_length=200)),
                ('scheduled_time', models.DateTimeField(db_index=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='doctor.doctor')),
            ],
            options={
                'ordering': ['-submitted_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('related_booking_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='appointments.patientbookingrequest')),
            ],
            options={
                'ordering': ['-created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('scheduled_day', models.DateField(blank=True, db_index=True, editable=False, null=True)),
                ('queue_number', models.PositiveIntegerField(blank=True, null=True)),
                ('iqd_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctor.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patient.patient')),
            ],
            options={
                'ordering': ['scheduled_time', 'pk'],
                'indexes': [models.Index(fields=['doctor', 'scheduled_day', 'status'], name='idx_doc_day_status')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('scheduled_time__isnull', False), models.Q(('status', 'cancelled'), _negated=True)), fields=('doctor', 'scheduled_time'), name='uq_doctor_time_not_cancelled'), models.UniqueConstraint(condition=models.Q(('scheduled_day__isnull', False), ('queue_number__isnull', False), models.Q(('status', 'cancelled'), _negated=True)), fields=('doctor', 'scheduled_day', 'queue_number'), name='uq_doctor_day_queue_active')],
            },
        ),
    ]
