# Generated by Django 5.2.4 on 2025-11-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientbookingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('requested', 'Requested'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
    ]
