# Generated by Django 5.2.4 on 2025-11-28 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_patientbookingrequest_status'),
        ('patient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientbookingrequest',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_requests', to='patient.patient'),
        ),
        migrations.AddField(
            model_name='patientbookingrequest',
            name='seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Seen at'),
        ),
        migrations.AddField(
            model_name='patientbookingrequest',
            name='seen_by_secretary',
            field=models.BooleanField(db_index=True, default=False, help_text='Marked as True once a secretary has viewed this request.'),
        ),
        migrations.AddField(
            model_name='patientbookingrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
