# Generated by Django 5.2.4 on 2026-01-05 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_patientbookingrequest_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='queue_number',
            field=models.PositiveIntegerField(blank=True, help_text='Auto-generated per doctor per day.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
