# Generated by Django 5.2.4 on 2026-01-18 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_queue_number'),
        ('doctor', '0014_doctorvisit_and_more'),
        ('patient', '0003_alter_patient_mobile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='uq_doctor_time_not_cancelled',
        ),
        migrations.RemoveConstraint(
            model_name='appointment',
            name='uq_doctor_day_queue_active',
        ),
        migrations.AddField(
            model_name='appointment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('scheduled_time__isnull', False), ('is_deleted', False), models.Q(('status', 'cancelled'), _negated=True)), fields=('doctor', 'scheduled_time'), name='uq_doctor_time_not_cancelled'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('scheduled_day__isnull', False), ('queue_number__isnull', False), ('is_deleted', False), models.Q(('status', 'cancelled'), _negated=True)), fields=('doctor', 'scheduled_day', 'queue_number'), name='uq_doctor_day_queue_active'),
        ),
    ]
