# Generated by Django 5.2.4 on 2026-07-10 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_remove_appointment_uq_doctor_time_not_cancelled_and_more'),
        ('doctor', '0014_doctorvisit_and_more'),
        ('hospital', '0002_staffassignment'),
        ('patient', '0003_alter_patient_mobile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='hospital.branch'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='hospital.department'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='hospital.hospital'),
        ),
        migrations.AddField(
            model_name='patientbookingrequest',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking_requests', to='hospital.branch'),
        ),
        migrations.AddField(
            model_name='patientbookingrequest',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking_requests', to='hospital.department'),
        ),
        migrations.AddField(
            model_name='patientbookingrequest',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking_requests', to='hospital.hospital'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['hospital', 'branch', 'scheduled_day'], name='idx_appt_hosp_branch_day'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['department', 'scheduled_day', 'status'], name='idx_appt_dept_day_status'),
        ),
        migrations.AddIndex(
            model_name='patientbookingrequest',
            index=models.Index(fields=['hospital', 'branch', 'scheduled_time'], name='idx_request_hosp_branch'),
        ),
        migrations.AddIndex(
            model_name='patientbookingrequest',
            index=models.Index(fields=['department', 'status', 'scheduled_time'], name='idx_request_dept_status'),
        ),
    ]
