# Generated by Django 5.2.11 on 2026-02-23 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_remove_appointment_uq_doctor_time_not_cancelled_and_more'),
        ('doctor', '0014_doctorvisit_and_more'),
        ('patient', '0003_alter_patient_mobile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientbookingrequest',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_booking_request', to='appointments.appointment'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('called', 'Called'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='patientbookingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('requested', 'Requested'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], db_index=True, default='requested', max_length=20),
        ),
        migrations.AddIndex(
            model_name='patientbookingrequest',
            index=models.Index(fields=['doctor', 'status', 'seen_by_secretary'], name='idx_br_doc_status_seen'),
        ),
    ]
