# Generated by Django 5.2.4 on 2026-01-08 18:05

import lab.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(default='ClinicHub Lab', max_length=120)),
                ('lab_phone', models.CharField(blank=True, default='', max_length=40)),
                ('lab_address', models.CharField(blank=True, default='', max_length=200)),
                ('lab_logo', models.ImageField(blank=True, null=True, upload_to='lab/settings/%Y/%m/')),
                ('max_upload_mb', models.PositiveIntegerField(default=10)),
                ('allow_pdf', models.BooleanField(default=True)),
                ('allow_images', models.BooleanField(default=True)),
                ('require_verify_before_ready', models.BooleanField(default=True)),
                ('default_result_template', models.TextField(blank=True, default='', help_text='Optional default text that appears in result form/report.')),
                ('footer_note', models.CharField(blank=True, default='', help_text='Optional footer note for lab reports.', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lab Settings',
                'verbose_name_plural': 'Lab Settings',
            },
        ),
        migrations.AlterField(
            model_name='laborder',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=lab.models._lab_result_upload_path),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='result_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
