# Generated by Django 5.2.4 on 2026-01-09 11:52

import django.core.validators
import lab.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_labsettings_alter_laborder_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='doctor_attachment',
            field=models.FileField(blank=True, help_text='Optional: Upload a PDF (referral/old report) to help the lab.', null=True, upload_to=lab.models._doctor_attachment_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Doctor PDF Attachment'),
        ),
    ]
