# Generated by Django 5.2.4 on 2026-01-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_laborder_doctor_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='doctor_seen_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the doctor opened/viewed this order after it became READY.', null=True),
        ),
    ]
