# Generated by Django 5.2.4 on 2026-01-31 15:41

import django.core.validators
import lab.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "appointments",
            "0005_remove_appointment_uq_doctor_time_not_cancelled_and_more",
        ),
        ("doctor", "0014_doctorvisit_and_more"),
        ("lab", "0004_laborder_doctor_seen_at"),
        ("patient", "0003_alter_patient_mobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="laborder",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("IN_PROGRESS", "In Progress"),
                    ("READY", "Ready"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="PENDING",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="labresult",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="Optional: upload PDF or image (jpg/png/webp).",
                null=True,
                upload_to=lab.models._lab_result_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["pdf", "jpg", "jpeg", "png", "webp"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="labresult",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("VERIFIED", "Verified")],
                db_index=True,
                default="DRAFT",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="laborder",
            index=models.Index(
                fields=["doctor", "status", "created_at"],
                name="lab_laborde_doctor__17ebaa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="laborder",
            index=models.Index(
                fields=["patient", "created_at"], name="lab_laborde_patient_625ac8_idx"
            ),
        ),
    ]
