# Generated by Django 5.2.4 on 2026-08-27 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_notification_action_url_and_more'),
        ('doctor', '0015_doctoranalyticsaccess_patientreportexportaccess'),
        ('hospital', '0002_staffassignment'),
        ('lab', '0005_alter_laborder_status_alter_labresult_attachment_and_more'),
        ('patient', '0003_alter_patient_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Creation-time tenant ownership snapshot.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders', to='hospital.branch'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text='Creation-time tenant ownership snapshot.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders', to='hospital.hospital'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['hospital', 'branch', 'created_at'], name='lab_laborde_hospita_c3756c_idx'),
        ),
    ]
