# Generated by Django 5.2.4 on 2026-09-18 13:22

import core.private_storage
import django.core.validators
import lab.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_laborder_branch_laborder_hospital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborder',
            name='doctor_attachment',
            field=models.FileField(blank=True, help_text='Optional: Upload a PDF (referral/old report) to help the lab.', null=True, storage=core.private_storage.PrivateClinicalStorage(), upload_to=lab.models._doctor_attachment_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Doctor PDF Attachment'),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional: upload PDF or image (jpg/png/webp).', null=True, storage=core.private_storage.PrivateClinicalStorage(), upload_to=lab.models._lab_result_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
