# Generated by Django 5.2.4 on 2026-07-10 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('hospital_admin', 'Hospital Admin'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('secretary', 'Secretary'), ('receptionist', 'Receptionist'), ('pharmacist', 'Pharmacist'), ('lab_technician', 'Lab Technician'), ('radiologist', 'Radiologist'), ('accountant', 'Accountant')], db_index=True, max_length=30)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_assignments', to='hospital.branch')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_assignments', to='hospital.department')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_assignments', to='hospital.hospital')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospital_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['hospital_id', 'branch_id', 'department_id', 'user_id'],
                'indexes': [models.Index(fields=['user', 'hospital', 'is_active'], name='staff_user_hosp_active_idx'), models.Index(fields=['hospital', 'branch', 'department'], name='staff_location_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('is_primary', True)), fields=('user',), name='unique_primary_staff_assignment')],
            },
        ),
    ]
