# Generated by Django 5.2.4 on 2025-11-29 14:14

import django.core.validators
import doctor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.CharField(blank=True, help_text='E.164-like: optional +, 7–15 digits.', max_length=20, null=True, validators=[doctor.models.validate_phone], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, help_text='JPEG, PNG, or GIF; max 2 MB.', null=True, upload_to=doctor.models._upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])], verbose_name='Profile Photo'),
        ),
    ]
