# Generated by Django 5.2.4 on 2025-12-21 11:58

import django.core.validators
import django.db.models.deletion
import doctor.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_doctor_phone_alter_doctor_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='clinic_logo',
            field=models.ImageField(blank=True, help_text='Used as watermark/header logo in prescription templates. Max 2 MB.', null=True, upload_to=doctor.models.doctor_brand_upload_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])], verbose_name='Clinic Logo'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='prescription_header_illustration',
            field=models.FileField(blank=True, help_text='Optional illustration for prescription header. If empty, Specialty icon is used.', null=True, upload_to=doctor.models.doctor_brand_upload_to, validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg', 'webp'])], verbose_name='Prescription Header Illustration'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='signature_image',
            field=models.ImageField(blank=True, help_text='Optional digital signature image. Max 2 MB.', null=True, upload_to=doctor.models.doctor_brand_upload_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])], verbose_name='Doctor Signature Image'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, help_text='JPEG/PNG/GIF/WEBP; max 2 MB.', null=True, upload_to=doctor.models.doctor_photo_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='Profile Photo'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(db_index=True, default='General', help_text='Legacy text specialty. You can keep it or map it to Specialty Profile.', max_length=100, verbose_name='Specialty (Text)'),
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: Dermatology, Cardiology, General Surgery.', max_length=120, unique=True, verbose_name='Specialty Name')),
                ('code', models.SlugField(help_text='URL/identifier-friendly code. Example: dermatology, cardiology.', max_length=80, unique=True, verbose_name='Code')),
                ('icon', models.FileField(blank=True, help_text='SVG is recommended for best quality. PNG/JPG also supported.', null=True, upload_to=doctor.models.specialty_asset_upload_to, validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg', 'webp'])], verbose_name='Specialty Icon / Illustration')),
                ('primary_color', models.CharField(blank=True, help_text='Example: #2563eb', max_length=20, verbose_name='Primary Color')),
                ('accent_color', models.CharField(blank=True, help_text='Example: #0d9488', max_length=20, verbose_name='Accent Color')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Specialty',
                'verbose_name_plural': 'Specialties',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='doctor_spec_code_86dff2_idx'), models.Index(fields=['name'], name='doctor_spec_name_94d703_idx')],
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty_profile',
            field=models.ForeignKey(blank=True, help_text='Pick a specialty profile to enable icons/branding.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='doctor.specialty', verbose_name='Specialty Profile'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['specialty_profile'], name='doctor_doct_special_574af1_idx'),
        ),
    ]
