# Generated by Django 5.2.4 on 2025-12-25 17:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctor_clinic_logo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='syndicate_registration_date',
            field=models.DateField(blank=True, db_index=True, help_text='Date of registration in the syndicate (e.g., Iraqi Medical Association).', null=True, verbose_name='Syndicate Registration Date'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='syndicate_registration_no',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Optional: doctor registration number in the syndicate.', max_length=80, verbose_name='Syndicate Registration No.'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['syndicate_registration_no'], name='doctor_doct_syndica_33640c_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['syndicate_registration_date'], name='doctor_doct_syndica_95e8f8_idx'),
        ),
    ]
