# Generated by Django 5.2.4 on 2025-12-25 22:06

import django.core.validators
import doctor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_doctor_syndicate_registration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='prescription_watermark',
            field=models.FileField(blank=True, help_text='Optional watermark for prescriptions. If empty, Specialty icon can be used as default.', null=True, upload_to=doctor.models.doctor_brand_upload_to, validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg', 'webp'])], verbose_name='Prescription Watermark'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='clinic_logo',
            field=models.ImageField(blank=True, help_text='Optional. Can be used in some templates. Max 2 MB.', null=True, upload_to=doctor.models.doctor_brand_upload_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])], verbose_name='Clinic Logo'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='prescription_header_illustration',
            field=models.FileField(blank=True, help_text='Optional illustration for prescription header. If empty, Specialty icon may be used.', null=True, upload_to=doctor.models.doctor_brand_upload_to, validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg', 'webp'])], verbose_name='Prescription Header Illustration'),
        ),
    ]
