# Generated by Django 5.2.4 on 2025-12-26 18:09

import doctor.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_doctor_prescription_watermark_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='accent_color',
            field=models.CharField(blank=True, default='', help_text='Optional. Overrides specialty accent color. Example: #0d9488', max_length=20, verbose_name='Accent Color (Doctor Override)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='primary_color',
            field=models.CharField(blank=True, default='', help_text='Optional. Overrides specialty primary color. Example: #0b4ea2', max_length=20, verbose_name='Primary Color (Doctor Override)'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='clinic_address',
            field=models.TextField(blank=True, default='', help_text='Clinic address as shown on prescriptions and profiles.', verbose_name='Clinic Address'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='full_name',
            field=models.CharField(blank=True, default='', help_text='If empty, it will be filled from user.get_full_name() or username.', max_length=255, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='', max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.CharField(blank=True, db_index=True, help_text='E.164-like: optional +, 7–15 digits.', max_length=20, null=True, validators=[doctor.models.validate_phone], verbose_name='Clinic Phone Number'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='short_bio',
            field=models.CharField(blank=True, default='', help_text='Brief summary shown on profile card.', max_length=255, verbose_name='Short Biography'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='accent_color',
            field=models.CharField(blank=True, default='', help_text='Example: #0d9488', max_length=20, verbose_name='Accent Color'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='primary_color',
            field=models.CharField(blank=True, default='', help_text='Example: #2563eb', max_length=20, verbose_name='Primary Color'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['phone'], name='doctor_doct_phone_79fcaf_idx'),
        ),
    ]
