# Generated by Django 5.2.4 on 2025-12-30 20:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_doctor_accent_color_doctor_primary_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='entity_type',
            field=models.CharField(choices=[('doctor_m', 'Doctor (Male)'), ('doctor_f', 'Doctor (Female)'), ('clinic', 'Clinic')], db_index=True, default='doctor_m', help_text='Choose whether this profile is a male doctor, female doctor, or a clinic.', max_length=10, verbose_name='Entity Type'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['entity_type'], name='doctor_doct_entity__3e638a_idx'),
        ),
    ]
