# Generated by Django 5.2.4 on 2026-01-07 10:24

import doctor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_doctor_entity_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='prescription_header_bg',
            field=models.CharField(blank=True, default='', help_text='Example: #FDE7D6 (leave blank to auto from primary).', max_length=7, validators=[doctor.models.validate_hex_or_blank], verbose_name='Prescription Header Card Background (HEX)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='prescription_paper_bg',
            field=models.CharField(blank=True, default='', help_text='Example: #FFFFFF (leave blank to use default).', max_length=7, validators=[doctor.models.validate_hex_or_blank], verbose_name='Prescription Paper Background (HEX)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='prescription_paper_border',
            field=models.CharField(blank=True, default='', help_text='Example: #E9ECEF (leave blank to use default).', max_length=7, validators=[doctor.models.validate_hex_or_blank], verbose_name='Prescription Paper Border (HEX)'),
        ),
    ]
