# Generated by Django 5.2.4 on 2026-01-08 06:52

import doctor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_doctor_prescription_header_bg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='prescription_header_text_color',
            field=models.CharField(blank=True, default='', help_text='Example: #000000 (leave blank to use default).', max_length=7, validators=[doctor.models.validate_hex_or_blank], verbose_name='Prescription Header Text Color (HEX)'),
        ),
    ]
