# Generated by Django 5.2.4 on 2026-01-08 07:46

import doctor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_doctor_prescription_header_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='prescription_header_line_color',
            field=models.CharField(blank=True, default='', help_text='Example: #E5E7EB (leave blank to use default).', max_length=7, validators=[doctor.models.validate_hex_or_blank], verbose_name='Prescription Header Line Color (HEX)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='prescription_patient_label_color',
            field=models.CharField(blank=True, default='', help_text='Example: #64748B (leave blank to use default).', max_length=7, validators=[doctor.models.validate_hex_or_blank], verbose_name='Prescription Patient Labels Color (HEX)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='prescription_patient_value_color',
            field=models.CharField(blank=True, default='', help_text='Example: #0F172A (leave blank to use default).', max_length=7, validators=[doctor.models.validate_hex_or_blank], verbose_name='Prescription Patient Values Color (HEX)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='prescription_specialty_text_color',
            field=models.CharField(blank=True, default='', help_text='Example: #334155 (leave blank to use default).', max_length=7, validators=[doctor.models.validate_hex_or_blank], verbose_name='Prescription Specialty Text Color (HEX)'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='prescription_header_text_color',
            field=models.CharField(blank=True, default='', help_text='Example: #111827 (leave blank to use default).', max_length=7, validators=[doctor.models.validate_hex_or_blank], verbose_name='Prescription Header Text Color (HEX)'),
        ),
    ]
