# Generated by Django 5.2.4 on 2026-01-11 09:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_doctor_prescription_header_line_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(db_index=True, help_text='1 to 5 stars.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Doctor Review',
                'verbose_name_plural': 'Doctor Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='doctor',
            name='doctor_rating_between_0_and_5',
        ),
        migrations.AddField(
            model_name='doctor',
            name='review_count',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, help_text='Auto-calculated reviews count.', verbose_name='Review Count (Auto)'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated average rating from reviews (0–5).', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Rating (Auto)'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['review_count'], name='doctor_doct_review__b76dfa_idx'),
        ),
        migrations.AddConstraint(
            model_name='doctor',
            constraint=models.CheckConstraint(condition=models.Q(('rating__isnull', True), models.Q(('rating__gte', 0), ('rating__lte', 5)), _connector='OR'), name='doctor_rating_null_or_between_0_and_5'),
        ),
        migrations.AddField(
            model_name='doctorreview',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='doctor.doctor', verbose_name='Doctor'),
        ),
        migrations.AddField(
            model_name='doctorreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Reviewer'),
        ),
        migrations.AddIndex(
            model_name='doctorreview',
            index=models.Index(fields=['doctor', 'created_at'], name='doctor_doct_doctor__3eb758_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorreview',
            index=models.Index(fields=['doctor', 'rating'], name='doctor_doct_doctor__15b962_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorreview',
            index=models.Index(fields=['reviewer', 'created_at'], name='doctor_doct_reviewe_c4c3c3_idx'),
        ),
        migrations.AddConstraint(
            model_name='doctorreview',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='doctorreview_rating_between_1_and_5'),
        ),
    ]
