# Generated by Django 5.2.4 on 2026-01-12 07:03

import django.core.validators
import doctor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_doctorreview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='cover_photo',
            field=models.ImageField(blank=True, help_text='Wide cover image shown on top of doctor cards. Max 2 MB.', null=True, upload_to=doctor.models.doctor_cover_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='Card Cover Photo'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, help_text='Square profile photo (avatar). JPEG/PNG/GIF/WEBP; max 2 MB.', null=True, upload_to=doctor.models.doctor_photo_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='Profile Photo'),
        ),
    ]
