# Generated by Django 5.2.4 on 2026-01-12 15:24

import doctor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_doctor_cover_photo_alter_doctor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True, help_text='If disabled, this specialty will not appear in public filters/pages.', verbose_name='Show Publicly'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='accent_color',
            field=models.CharField(blank=True, default='', help_text='Example: #0d9488 (leave blank for default).', max_length=20, validators=[doctor.models.validate_hex_or_blank], verbose_name='Accent Color'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='primary_color',
            field=models.CharField(blank=True, default='', help_text='Example: #2563eb (leave blank for default).', max_length=20, validators=[doctor.models.validate_hex_or_blank], verbose_name='Primary Color'),
        ),
        migrations.AddIndex(
            model_name='specialty',
            index=models.Index(fields=['is_public'], name='doctor_spec_is_publ_849b5f_idx'),
        ),
    ]
