# Generated by Django 5.2.4 on 2026-01-16 14:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import doctor.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_queue_number'),
        ('doctor', '0013_specialty_is_public_alter_specialty_accent_color_and_more'),
        ('patient', '0003_alter_patient_mobile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.CharField(max_length=255, verbose_name='Chief Complaint')),
                ('symptoms', models.TextField(verbose_name='Symptoms')),
                ('history', models.TextField(blank=True, default='', verbose_name='History')),
                ('examination', models.TextField(blank=True, default='', verbose_name='Examination')),
                ('preliminary_diagnosis', models.CharField(blank=True, default='', max_length=255, verbose_name='Preliminary Diagnosis')),
                ('final_diagnosis', models.CharField(blank=True, default='', max_length=255, verbose_name='Final Diagnosis')),
                ('plan', models.TextField(blank=True, default='', verbose_name='Plan / Notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Doctor Visit',
                'verbose_name_plural': 'Doctor Visits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='doctor',
            name='unique_doctor_phone_nonempty',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='clinic_logo',
            field=models.ImageField(blank=True, help_text='Optional. Max 2 MB.', null=True, upload_to=doctor.models.doctor_brand_upload_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])], verbose_name='Clinic Logo'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='cover_photo',
            field=models.ImageField(blank=True, help_text='Wide cover shown on doctor cards. Max 2 MB.', null=True, upload_to=doctor.models.doctor_cover_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='Card Cover Photo'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='entity_type',
            field=models.CharField(choices=[('doctor_m', 'Doctor (Male)'), ('doctor_f', 'Doctor (Female)'), ('clinic', 'Clinic')], db_index=True, default='doctor_m', help_text='Male doctor, female doctor, or clinic.', max_length=10, verbose_name='Entity Type'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, help_text='Square profile photo (avatar). Max 2 MB.', null=True, upload_to=doctor.models.doctor_photo_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='Profile Photo'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='prescription_header_illustration',
            field=models.FileField(blank=True, help_text='Optional. If empty, Specialty icon may be used.', null=True, upload_to=doctor.models.doctor_brand_upload_to, validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg', 'webp'])], verbose_name='Prescription Header Illustration'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='prescription_watermark',
            field=models.FileField(blank=True, help_text='Optional. If empty, Specialty icon can be used.', null=True, upload_to=doctor.models.doctor_brand_upload_to, validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg', 'webp'])], verbose_name='Prescription Watermark'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='signature_image',
            field=models.ImageField(blank=True, help_text='Optional. Max 2 MB.', null=True, upload_to=doctor.models.doctor_brand_upload_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])], verbose_name='Doctor Signature Image'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='syndicate_registration_date',
            field=models.DateField(blank=True, db_index=True, help_text='Date of registration in the syndicate.', null=True, verbose_name='Syndicate Registration Date'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='syndicate_registration_no',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Optional doctor registration number in the syndicate.', max_length=80, verbose_name='Syndicate Registration No.'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='icon',
            field=models.FileField(blank=True, help_text='SVG recommended. PNG/JPG also supported.', null=True, upload_to=doctor.models.specialty_asset_upload_to, validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg', 'webp'])], verbose_name='Specialty Icon / Illustration'),
        ),
        migrations.AddConstraint(
            model_name='doctor',
            constraint=models.UniqueConstraint(condition=models.Q(('phone__isnull', False), models.Q(('phone', ''), _negated=True)), fields=('phone',), name='unique_doctor_phone_nonempty'),
        ),
        migrations.AddField(
            model_name='doctorvisit',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visit', to='appointments.appointment', verbose_name='Appointment'),
        ),
        migrations.AddField(
            model_name='doctorvisit',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='doctor.doctor', verbose_name='Doctor'),
        ),
        migrations.AddField(
            model_name='doctorvisit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patient.patient', verbose_name='Patient'),
        ),
        migrations.AddIndex(
            model_name='doctorvisit',
            index=models.Index(fields=['doctor', 'created_at'], name='doctor_doct_doctor__0e40a4_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorvisit',
            index=models.Index(fields=['patient', 'created_at'], name='doctor_doct_patient_9b9977_idx'),
        ),
    ]
