# Generated by Django 5.2.4 on 2026-08-01 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0014_doctorvisit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAnalyticsAccess',
            fields=[
            ],
            options={
                'verbose_name': 'Reports & Analytics',
                'verbose_name_plural': 'Reports & Analytics',
                'proxy': True,
                'default_permissions': ('view',),
                'indexes': [],
                'constraints': [],
            },
            bases=('doctor.doctor',),
        ),
        migrations.CreateModel(
            name='PatientReportExportAccess',
            fields=[
            ],
            options={
                'verbose_name': 'Generate Patient Report',
                'verbose_name_plural': 'Generate Patient Reports',
                'proxy': True,
                'default_permissions': ('view',),
                'indexes': [],
                'constraints': [],
            },
            bases=('doctor.doctor',),
        ),
    ]
