# Generated by Django 5.2.11 on 2026-03-03 09:14

import django.core.validators
import doctor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0014_doctorvisit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='accent_color',
            field=models.CharField(blank=True, default='', help_text='Optional. Overrides specialty accent color. Example: #0d9488', max_length=20, validators=[doctor.models.validate_hex_or_blank], verbose_name='Accent Color (Doctor Override)'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Available for Booking'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='clinic_address',
            field=models.TextField(blank=True, default='', verbose_name='Clinic Address'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='clinic_logo',
            field=models.ImageField(blank=True, null=True, upload_to=doctor.models.doctor_brand_upload_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])], verbose_name='Clinic Logo'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='consultation_fee',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Consultation Fee (IQD)'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to=doctor.models.doctor_cover_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='Card Cover Photo'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(80)], verbose_name='Years of Experience'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, validators=[doctor.models.validate_phone], verbose_name='Clinic Phone Number'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=doctor.models.doctor_photo_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='Profile Photo'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='prescription_header_bg',
            field=models.CharField(blank=True, default='', max_length=7, validators=[doctor.models.validate_hex_or_blank], verbose_name='Prescription Header Card Background (HEX)'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='prescription_header_illustration',
            field=models.FileField(blank=True, null=True, upload_to=doctor.models.doctor_brand_upload_to, validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg', 'webp'])], verbose_name='Prescription Header Illustration'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='prescription_header_line_color',
            field=models.CharField(blank=True, default='', max_length=7, validators=[doctor.models.validate_hex_or_blank], verbose_name='Prescription Header Line Color (HEX)'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='prescription_header_text_color',
            field=models.CharField(blank=True, default='', max_length=7, validators=[doctor.models.validate_hex_or_blank], verbose_name='Prescription Header Text Color (HEX)'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='prescription_paper_bg',
            field=models.CharField(blank=True, default='', max_length=7, validators=[doctor.models.validate_hex_or_blank], verbose_name='Prescription Paper Background (HEX)'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='prescription_paper_border',
            field=models.CharField(blank=True, default='', max_length=7, validators=[doctor.models.validate_hex_or_blank], verbose_name='Prescription Paper Border (HEX)'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='prescription_patient_label_color',
            field=models.CharField(blank=True, default='', max_length=7, validators=[doctor.models.validate_hex_or_blank], verbose_name='Prescription Patient Labels Color (HEX)'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='prescription_patient_value_color',
            field=models.CharField(blank=True, default='', max_length=7, validators=[doctor.models.validate_hex_or_blank], verbose_name='Prescription Patient Values Color (HEX)'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='prescription_specialty_text_color',
            field=models.CharField(blank=True, default='', max_length=7, validators=[doctor.models.validate_hex_or_blank], verbose_name='Prescription Specialty Text Color (HEX)'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='prescription_watermark',
            field=models.FileField(blank=True, null=True, upload_to=doctor.models.doctor_brand_upload_to, validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg', 'webp'])], verbose_name='Prescription Watermark'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='primary_color',
            field=models.CharField(blank=True, default='', help_text='Optional. Overrides specialty primary color. Example: #0b4ea2', max_length=20, validators=[doctor.models.validate_hex_or_blank], verbose_name='Primary Color (Doctor Override)'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Rating (Auto)'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='review_count',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Review Count (Auto)'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='short_bio',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Short Biography'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to=doctor.models.doctor_brand_upload_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])], verbose_name='Doctor Signature Image'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='syndicate_registration_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Syndicate Registration Date'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='syndicate_registration_no',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80, verbose_name='Syndicate Registration No.'),
        ),
    ]
