# Generated by Django 5.2.4 on 2026-09-18 13:35

import core.private_storage
import django.core.validators
import doctor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0015_doctoranalyticsaccess_patientreportexportaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='signature_image',
            field=models.ImageField(blank=True, help_text='Optional. Max 2 MB.', null=True, storage=core.private_storage.PrivateClinicalStorage(), upload_to=doctor.models.doctor_brand_upload_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])], verbose_name='Doctor Signature Image'),
        ),
    ]
